---
services:

  broker-1:
    environment:
      # Configuração KRaft
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_QUORUM_VOTERS:-'1@broker-1:29093,2@broker-2:29093,3@broker-3:29093'}
      KAFKA_LISTENERS: 'PLAINTEXT://:29092,SASL_PLAINTEXT://:9092,CONTROLLER://:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-1:29092,SASL_PLAINTEXT://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-3}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-3}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1

      # Configuração SASL/PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: 'SCRAM-SHA-256'
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'SCRAM-SHA-256'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT'
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kraft/kafka_server_jaas-scram.conf"
    volumes:
      - ./secrets/kafka_server_jaas.conf:/etc/kafka/kraft/kafka_server_jaas-scram.conf:ro

  broker-2:
    environment:
      # Configuração KRaft
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_QUORUM_VOTERS:-'1@broker-1:29093,2@broker-2:29093,3@broker-3:29093'}
      KAFKA_LISTENERS: 'PLAINTEXT://:29092,SASL_PLAINTEXT://:9092,CONTROLLER://:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-2:29092,SASL_PLAINTEXT://localhost:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-3}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-3}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1

      # Configuração SASL/PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: 'SCRAM-SHA-256'
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'SCRAM-SHA-256'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT'
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kraft/kafka_server_jaas-scram.conf"
    volumes:
      - ./secrets/kafka_server_jaas.conf:/etc/kafka/kraft/kafka_server_jaas-scram.conf:ro
      

  broker-3:
    environment:
      # Configuração KRaft
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_QUORUM_VOTERS:-'1@broker-1:29093,2@broker-2:29093,3@broker-3:29093'}
      KAFKA_LISTENERS: 'PLAINTEXT://:29092,SASL_PLAINTEXT://:9092,CONTROLLER://:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-3:29092,SASL_PLAINTEXT://localhost:9094'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-3}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-3}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1

      # Configuração SASL/PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: 'SCRAM-SHA-256'
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'SCRAM-SHA-256'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT'
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kraft/kafka_server_jaas-scram.conf"
    volumes:
      - ./secrets/kafka_server_jaas.conf:/etc/kafka/kraft/kafka_server_jaas-scram.conf:ro
      