---
services:

  broker-1:
    environment:
      # Configuração KRaft
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_QUORUM_VOTERS:-'1@broker-1:29093,2@broker-2:29093,3@broker-3:29093'}
      KAFKA_LISTENERS: 'PLAINTEXT://:29092,SASL_PLAINTEXT://:9092,CONTROLLER://:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-1:29092,SASL_PLAINTEXT://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-3}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-3}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1

      # Configuração SASL/PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: 'SCRAM-SHA-256,SCRAM-SHA-512'
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'SCRAM-SHA-256'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT'
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kraft/kafka_server_jaas-scram.conf -javaagent:/jmx/jmx_prometheus_javaagent-1.3.0.jar=7071:/jmx/kafka-metrics.yml"
    volumes:
      - ./secrets/kafka_server_jaas-scram.conf:/etc/kafka/kraft/kafka_server_jaas-scram.conf:ro
      - ./data/libs/jmx:/jmx:ro

  broker-2:
    environment:
      # Configuração KRaft
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_QUORUM_VOTERS:-'1@broker-1:29093,2@broker-2:29093,3@broker-3:29093'}
      KAFKA_LISTENERS: 'PLAINTEXT://:29092,SASL_PLAINTEXT://:9092,CONTROLLER://:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-2:29092,SASL_PLAINTEXT://localhost:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-3}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-3}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1

      # Configuração SASL/PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: 'SCRAM-SHA-256,SCRAM-SHA-512'
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'SCRAM-SHA-256'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT'
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kraft/kafka_server_jaas-scram.conf -javaagent:/jmx/jmx_prometheus_javaagent-1.3.0.jar=7071:/jmx/kafka-metrics.yml"
    volumes:
      - ./secrets/kafka_server_jaas-scram.conf:/etc/kafka/kraft/kafka_server_jaas-scram.conf:ro
      - ./data/libs/jmx:/jmx:ro
      

  broker-3:
    environment:
      # Configuração KRaft
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_QUORUM_VOTERS:-'1@broker-1:29093,2@broker-2:29093,3@broker-3:29093'}
      KAFKA_LISTENERS: 'PLAINTEXT://:29092,SASL_PLAINTEXT://:9092,CONTROLLER://:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-3:29092,SASL_PLAINTEXT://localhost:9094'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-3}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-3}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1

      # Configuração SASL/PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: 'SCRAM-SHA-256,SCRAM-SHA-512'
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'SCRAM-SHA-256'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT'
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kraft/kafka_server_jaas-scram.conf -javaagent:/jmx/jmx_prometheus_javaagent-1.3.0.jar=7071:/jmx/kafka-metrics.yml"
    volumes:
      - ./secrets/kafka_server_jaas-scram.conf:/etc/kafka/kraft/kafka_server_jaas-scram.conf:ro
      - ./data/libs/jmx:/jmx:ro
      
  kafka-init-users:
    image: confluentinc/cp-kafka:${CONFLUENTINC_VERSION:-7.9.1}
    container_name: kafka-init-users
    hostname: kafka-init-users
    depends_on:
      broker-1:
        condition: service_healthy
      broker-2:
        condition: service_healthy
      broker-3:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      sleep 20 && \
      kafka-configs --bootstrap-server broker-1:29092 --alter --add-config 'SCRAM-SHA-256=[password=admin-secret]' --entity-type users --entity-name admin && \
      kafka-configs --bootstrap-server broker-1:29092 --alter --add-config 'SCRAM-SHA-512=[password=admin-secret]' --entity-type users --entity-name admin && \
      kafka-configs --bootstrap-server broker-1:29092 --alter --add-config 'SCRAM-SHA-256=[password=producer-secret]' --entity-type users --entity-name producer_app && \
      kafka-configs --bootstrap-server broker-1:29092 --alter --add-config 'SCRAM-SHA-512=[password=producer-secret]' --entity-type users --entity-name producer_app && \
      kafka-configs --bootstrap-server broker-1:29092 --alter --add-config 'SCRAM-SHA-256=[password=consumer-secret]' --entity-type users --entity-name consumer_app && \
      kafka-configs --bootstrap-server broker-1:29092 --alter --add-config 'SCRAM-SHA-512=[password=consumer-secret]' --entity-type users --entity-name consumer_app
      "
    networks:
      - kafka-net